import { IExpenses } from "~/core/models/expenses";

export const expenses: IExpenses = {
  days: [
    {
      date: "01.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "02.01.2020",
      status: "fail",
      info: "Games, PlayStation...",
      spentMoney: 220,
    },
    {
      date: "03.01.2020",
      status: "success",
      info: "Goods, tea...",
      spentMoney: 120,
    },
    {
      date: "04.01.2020",
      status: "success",
      info: "Cat food, phone",
      spentMoney: 120,
    },
    {
      date: "05.01.2020",
      status: "fail",
      info: "Car, phone...",
      spentMoney: 250,
    },
    {
      date: "06.01.2020",
      status: "fail",
      info: "Goods, coffee",
      spentMoney: 230,
    },
    {
      date: "07.01.2020",
      status: "fail",
      info: "Goods, phone",
      spentMoney: 205,
    },
    {
      date: "08.01.2020",
      status: "success",
      info: "Bike, phone",
      spentMoney: 190,
    },
    {
      date: "09.01.2020",
      status: "fail",
      info: "Goods, phone",
      spentMoney: 200,
    },
    {
      date: "10.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 100,
    },
    {
      date: "11.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "12.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 100,
    },
    {
      date: "13.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 200,
    },
    {
      date: "14.01.2020",
      status: "fail",
      info: "Goods, phone",
      spentMoney: 300,
    },
    {
      date: "15.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "16.01.2020",
      status: "fail",
      info: "Goods, phone",
      spentMoney: 290,
    },
    {
      date: "17.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "18.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "19.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "20.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "21.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "22.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "23.01.2020",
      status: "fail",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "24.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "25.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "26.01.2020",
      status: "fail",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "27.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "28.01.2020",
      status: "success",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "29.01.2020",
      status: "fail",
      info: "Goods, phone",
      spentMoney: 120,
    },
    {
      date: "30.01.2020",
      status: "fail",
      info: "Goods, phone",
      spentMoney: 120,
    },
    { date: "31.01.2020", status: null, info: "Goods, phone", spentMoney: 120 },
  ],
};
